
export enum eTrackingStatus {
    ORDER_RECEIVED = 'ORDER_RECEIVED',
    PROCESSING = 'PROCESSING',
    SHIPPED = 'SHIPPED',
    IN_TRANSIT = 'IN_TRANSIT',
    OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
    DELIVERED = 'DELIVERED',
    CANCELLED = 'CANCELLED',
    DELAYED = 'DELAYED',
}
